### ISSUE TITLE
question about the scope

### ISSUE THREAD

**Issue by dyabel** [baudm/MONet-pytorch#14]
https://github.com/baudm/MONet-pytorch/blob/75239c6e74e4947b6728ffb615e8e81b24718a7e/models/monet_model.py#L86C33-L86C33

log_s_k += -alpha_logits_k + log_alpha_k
why is scope computed this way, it is not equivalent to s_k = s_k * (1-alpha_k) in the paper

**Comment by baudm** [comment]
See PR #8 and commit 334c578936bbd9d49f5d0122de8f5ce17eac1f45
