### ISSUE TITLE
Something wrong with ./scripts/generate_monet_montage.sh after testing using pre-trained model

### ISSUE THREAD

**Issue by HymEric** [baudm/MONet-pytorch#6]
![image](https://user-images.githubusercontent.com/26487821/80169141-477d8680-8617-11ea-8851-456d18a063ea.png)

**Comment by baudm** [comment]
Please re-run the following commands:
```
./scripts/download_monet_model.sh clevr
./scripts/test_monet.sh
./scripts/generate_monet_montage.sh
```
The resulting montages should be in `./results/clevr_monet_pretrained/test_latest/`

**Comment by HymEric** [comment]
Thank you very much.
