### ISSUE TITLE
AttributeError: Can't pickle local object 'StringEncoder.<locals>.EncodeField'

### ISSUE THREAD

**Issue by DilipSams** [baudm/MONet-pytorch#9]
Windows 10, torch version 1.5.1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-84-f1afae3e5ee4> in <module>
      2 import dill
      3 #from pathos.multiprocessing import ProcessingPool as Pool
----> 4 tr_it = iter(train_dataloader)
      5 progress_bar = tqdm(range(cfg["train_params"]["max_num_steps"]))
      6 losses_train = []

c:\users\dilip\anaconda3\envs\tf-gpu\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    277             return _SingleProcessDataLoaderIter(self)
    278         else:
--> 279             return _MultiProcessingDataLoaderIter(self)
    280 
    281     @property

c:\users\dilip\anaconda3\envs\tf-gpu\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    717             #     before it starts, and __del__ tries to join but will get:
    718             #     AssertionError: can only join a started process.
--> 719             w.start()
    720             self._index_queues.append(index_queue)
    721             self._workers.append(w)

c:\users\dilip\anaconda3\envs\tf-gpu\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

c:\users\dilip\anaconda3\envs\tf-gpu\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

c:\users\dilip\anaconda3\envs\tf-gpu\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

c:\users\dilip\anaconda3\envs\tf-gpu\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

c:\users\dilip\anaconda3\envs\tf-gpu\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

AttributeError: Can't pickle local object 'StringEncoder.<locals>.EncodeField'

**Comment by baudm** [comment]
Doesn't seem to be remotely related to this project. Probably a bug specific to your environment (Anaconda, Windows). I don't use PyTorch on Windows so I am unable to replicate this.
